version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    command:
      - etcd
      - --advertise-client-urls=http://etcd:2379
      - --listen-client-urls=http://0.0.0.0:2379
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health", "--endpoints=http://localhost:2379"]
      interval: 10s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    command: server /minio_data --console-address ":9001"
    environment:
      MINIO_ROOT_USER:  minioadmin
      MINIO_ROOT_PASSWORD:  minioadmin
    healthcheck:
      test: ["CMD", "mc", "admin", "info", "local"]
      interval: 10s
      retries: 5

  standalone:
    image: milvusdb/milvus:v2.3.3
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ENDPOINT: http://minio:9000
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 19530"]
      interval: 10s
      retries: 5

  ui:
    image: hfregistry.azurecr.io/streamlit-ui:latest
    # map App Service port 80 → container 8501
    ports:
      - "80:8501"
    depends_on:
      standalone:
        condition: service_healthy
    # tell App Service “this is the one to health-check”
    labels:
      - "com.microsoft.azure.primary-container=true"
    environment:
      MILVUS_HOST: standalone
      MILVUS_PORT: 19530
      ETCD_ENDPOINT: etcd:2379
      MINIO_ENDPOINT: http://minio:9000
