FROM python:3.12-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# expose Streamlit port
ENV PORT=8501
ENTRYPOINT ["streamlit","run","qa_ui.py","--server.address=0.0.0.0","--server.port=8501"]
