version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    command: >
      etcd
      -advertise-client-urls=http://127.0.0.1:2379
      -listen-client-urls=http://0.0.0.0:2379
      --data-dir /etcd

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    command: minio server /minio_data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

  standalone:
    image: milvusdb/milvus:v2.3.3
    environment:
      ETCD_ENDPOINTS: 127.0.0.1:2379
      MINIO_ADDRESS: 127.0.0.1:9000
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
