version: '3.8'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    command: >
      etcd
      -advertise-client-urls=http://0.0.0.0:2379
      -listen-client-urls=http://0.0.0.0:2379
      --data-dir /etcd
    healthcheck:
      test: ["CMD-SHELL","ETCDCTL_API=3 etcdctl --endpoints=127.0.0.1:2379 endpoint health"]
      interval: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    command: minio server /minio_data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    healthcheck:
      test: ["CMD-SHELL","curl -f http://127.0.0.1:9000/minio/health/live"]
      interval: 5s
      retries: 5

  standalone:
    image: milvusdb/milvus:v2.3.3
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "19530:19530"
    entrypoint:
      - sh
      - -c
      - |
        echo "⏳ Waiting 30s for etcd & MinIO…"
        sleep 30
        echo "🚀 Starting Milvus"
        exec milvus run standalone
